# Generated by Django 5.0.3 on 2024-07-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identifiant',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
