# Generated by Django 5.0.3 on 2024-06-12 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriends',
            name='friends_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
