# Generated by Django 5.0.3 on 2024-06-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userfriends_friends_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfriends',
            old_name='friends_list',
            new_name='client_friends_list',
        ),
        migrations.RenameField(
            model_name='userfriends',
            old_name='uniqid',
            new_name='client_uniqid',
        ),
    ]
