# Generated by Django 5.0.3 on 2024-06-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_friends_list_userfriends_client_friends_list_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFriends',
        ),
    ]
